import {
    FiBook,
    FiBookmark,
    FiCode,
    FiCpu,
    FiHome,
    FiMic,
    FiPaperclip,
    FiUser,
    FiBriefcase
} from "react-icons/fi";

export const actions = [
    {
        id: "home",
        name: "Home",
        shortcut: ["h"],
        keywords: "home",
        perform: () => (window.location.pathname = "/"),
        section: "Navigation",
        icon: FiHome({ size: "1rem" }),
    },
    {
        id: "about",
        name: "About",
        shortcut: ["a"],
        keywords: "about",
        perform: () => (window.location.pathname = "/about"),
        section: "Navigation",
        icon: FiUser({ size: "1rem" }),
    },
    {
        id: "projects",
        name: "Projects",
        shortcut: ["p"],
        keywords: "projects",
        perform: () => (window.location.pathname = "/project"),
        section: "Navigation",
        icon: FiCode({ size: "1rem" }),
    },
    {
        id: "blog",
        name: "Blog",
        shortcut: ["b"],
        keywords: "writing words article blog",
        perform: () => (window.location.pathname = "/blog"),
        section: "Navigation",
        icon: FiBookmark({ size: "1rem" }),
    },
    {
        id: "bookshelf",
        name: "Bookshelf",
        shortcut: ["k"],
        keywords: "books reading bookshelf library",
        perform: () => (window.location.pathname = "/bookshelf"),
        section: "Navigation",
        icon: FiBook({ size: "1rem" }),
    },
    {
        id: "tech",
        name: "Tech",
        shortcut: ["t"],
        keywords: "tech stack tools gadgets ai llm vector databases",
        perform: () => (window.location.pathname = "/tech"),
        section: "Navigation",
        icon: FiCpu({ size: "1rem" }),
    },
    {
        id: "talks",
        name: "Talks",
        shortcut: ["m"],
        keywords: "talks notes field demos speaking ai agents",
        perform: () => (window.location.pathname = "/talks"),
        section: "Navigation",
        icon: FiMic({ size: "1rem" }),
    },
    {
        id: "links",
        name: "Links",
        shortcut: ["l"],
        keywords: "email link discord twitter github",
        perform: () => (window.location.pathname = "/links"),
        section: "Navigation",
        icon: FiPaperclip({ size: "1rem" }),
    },
    {
        id: "work",
        name: "Work",
        shortcut: ["w"],
        keywords: "work experience hyrecruitai ai product engineering",
        perform: () => (window.location.pathname = "/work"),
        section: "Navigation",
        icon: FiBriefcase({ size: "1rem" }),
    },
];
