import type { Project } from "./types"

export const projects: Project[] = [
    {
        title: "DevResume.",
        description: "Craft your developer Portfolio within Few Seconds.",
        image: "/devresume.png",
        gridSpan: "col-span-3 lg:col-span-2",
        backgroundColor: "bg-green-900 hover:bg-green-800",
        imageposition: "-right-4 lg:-right-[20%] -bottom-4 lg:-bottom-[20%]",
        url: "https://github.com/Abbhiishek/dresume",
        featured: true,
    },
    {
        title: "Wiidgets",
        description: "Only Api endpoint you need for GitHub widgets",
        image: "/wiidgets.png",
        gridSpan: "col-span-3 lg:col-span-1",
        backgroundColor: "bg-violet-900 hover:bg-violet-800",
        imageposition: "-left-4 lg:-left-[30%] -bottom-4 lg:-bottom-[10%]",
        url: "https://github.com/Abbhiishek/codecommunitymusic",
        featured: false,
    },
    {
        title: "Code Community Music",
        description: "CodeCommunityMusic is a community of developers and musicians who are passionate about music and code.",
        image: "/ccm.png",
        gridSpan: "col-span-3",
        backgroundColor: "bg-blue-900 hover:bg-blue-800",
        imageposition: "-right-4 lg:-right-[10%] -bottom-4 lg:-bottom-[5%]",
        url: "https://github.com/Abbhiishek/Widgets",
        featured: true,
    },
    {
        title: "Todoska",
        description: "Todoska is a simple Cli Todo-Tracker.",
        image: "/todoska.gif",
        gridSpan: "col-span-3 lg:col-span-2",
        backgroundColor: "bg-yellow-900 hover:bg-yellow-800",
        imageposition: "-right-4 lg:-right-[10%] -bottom-4 lg:-bottom-[35%]",
        url: "https://github.com/Abbhiishek/Todoska",
        featured: false,
    },
    {
        title: "Bashy",
        description: "Bashy is a url shortener on steroids.",
        image: "/bashy.png",
        gridSpan: "col-span-3 lg:col-span-1",
        backgroundColor: "bg-cyan-900 hover:bg-cyan-800",
        imageposition: "-right-4 lg:-right-[30%] -bottom-4 lg:-bottom-[10%]",
        url: "https://github.com/Abbhiishek/Bashy",
        featured: false,
    },
    {
        title: "Code.sh",
        description: "Code.sh is a simple and easy to use code sharing platform.",
        image: "/bashy.png",
        gridSpan: "col-span-3 lg:col-span-1",
        backgroundColor: "bg-indigo-900 hover:bg-indigo-800",
        imageposition: "-right-4 lg:-right-[30%] -bottom-4 lg:-bottom-[10%]",
        url: "https://github.com/Abbhiishek/codesh",
        featured: false,
    },
    {
        title: "Atom",
        description: "Event hosting platform for developers and tech enthusiasts.",
        image: "/bashy.png",
        gridSpan: "col-span-3 lg:col-span-2",
        backgroundColor: "bg-sky-900 hover:bg-sky-800",
        imageposition: "-right-4 lg:-right-[30%] -bottom-4 lg:-bottom-[10%]",
        url: "https://github.com/Abbhiishek/Bashy",
        featured: true,
    },
    {
        title: "Raise",
        description: "Raise is a one to one platform for startup founders to raise funds without any hassle.",
        image: "/bashy.png",
        gridSpan: "col-span-3",
        backgroundColor: "bg-amber-900 hover:bg-amber-800",
        imageposition: "-right-4 lg:-right-[30%] -bottom-4 lg:-bottom-[10%]",
        url: "https://github.com/Abbhiishek/Raise",
        featured: false,
    },
]

export function getFeaturedProjects(): Project[] {
    return projects.filter((p) => p.featured)
}
